<?php

namespace AppBundle\Repository;

/**
 * USERRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class USERRepository extends \Doctrine\ORM\EntityRepository
{
}
